// @index(['./svg/*.svg'], (f, _, e) => `${e.isFirst ? '/* export const iconlist = [ \n' : ''}    '${f.name}'${e.isLast ? '\n]; */' : ','}`)
/* export const iconlist = [ 
    'bookmark',
    'books',
    'cog',
    'compass',
    'css',
    'database',
    'display',
    'download',
    'earth',
    'edit',
    'film',
    'filter',
    'folder-o',
    'folder',
    'globe',
    'go',
    'goback',
    'home',
    'hsp',
    'html',
    'image',
    'lib',
    'link',
    'music',
    'profile',
    'studio',
    'text',
    'video'
]; */
// @endindex
